### PR TITLE
David17: Removed light grey background on odd posts and added dividing line between posts.

### LINKED ISSUE #51: topic page - post framing
At the moment, posts are set off from each other by a subtle alternation of background grey. That divides posters into two camps. I'd rather use a grey dividing line between posts (like in our current forum). I assume this could be done with some combination of top and/or bottom borders.

### PR DESCRIPTION
**Pull request by DavidScottBernstein**
Fixed #51 to frame posts, removed the grey background on every odd post.

### CODE REVIEW

**Comment by rgilman** [comment]
@DavidScottBernstein, great! I expect that `#ccc` will be fine for now. The goal is for the line to be unobtrusive but also strong enough so that when your eye gets to that part of the flow of conversation, you are cued into the break. If `#ccc` feels like that to you, let's go with it.

**Comment by DavidScottBernstein** [comment]
Yes, sounds good.

**Comment by iangilman** [comment]
I was imagining we would keep all of our BFCOM-specific styles below this marker in style.css:

```
/*********************/
/*    BFCom styles   */
/*********************/
```

That way they don't get mixed up with the styles we inherited. What do you think @DavidScottBernstein, @rgilman? 

The change looks good, but I'm noticing the `#ccc` border between the posts is darker than the `#eee` border around the posts (which comes from `.bbp-replies`). I figure they should match, so one or the other should change. I personally like `#eee` but perhaps it's a little too light for some of our audience... What do you guys think? I suppose there's always `#ddd` in the middle.

**Comment by DavidScottBernstein** [comment]
@iangilman I changed the post dividing line color to #ddd (#eee seemed too dark) and move the code to the bottom of Style.css in a new section called FORUMS. I added this to the David17 branch.

**Comment by iangilman** [comment]
Looks good, thank you! A possible follow-up would be to update the border on `.bbp-replies` to `#ddd` so they match. BTW, when you say "darker" I assume you mean lighter? :-)

**Pull request merged**
