### PR TITLE
Softened Author block

### LINKED ISSUE #52: topic page - author block
Here's what it currently looks like:

screen shot 2018-10-02 at 9 22 24 am

- It would be nice to round the corners on the picture to soften the energy.
- I'm not sure (haven't explored) to what extent our current system uses relative dates and what control we have over date formatting. There are a lot of cases to consider so that a wide range of dates will look good. The date type could be smaller or grayer than the name type.

### PR DESCRIPTION
**Pull request by DavidScottBernstein**
Fixed #52 by rounding corners of img.avatar and changing the font to be smaller, grey and italics.

### CODE REVIEW

**Comment by DavidScottBernstein** [comment]
@Robert I dropped the font of the date/time for posts in the author block to 8pt, grey, italics. You can change the date format from "F j, Y" to "Y-m-d" in the Wordpress UI so the date/time for entries fit on one line. As always, let me know if you'd like anything changed.

**Comment by DavidScottBernstein** [comment]
@iangilman I put the CSS code to software the author image block in the forum at the bottom of the file. It should land at the bottom of the /* FORUM */ section created in David17. Let me know if you'd like it to go somewhere else.

**Comment by robert** [comment]
@DavidScottBernstein I'm happy to review the code but I don't think you actually meant me ;)

**Comment by DavidScottBernstein** [comment]
Sorry, @robert I meant to send this to the other Robert, @rgilman: I dropped the font of the date/time for posts in the author block to 8pt, grey, italics. You can change the date format from "F j, Y" to "Y-m-d" in the Wordpress UI so the date/time for entries fit on one line. As always, let me know if you'd like anything changed.

**Comment by iangilman** [comment]
@DavidScottBernstein Looks good to me! BTW, one thing you can do to help with reviews is take a snapshot of what it looks like on your machine and paste it into here. To take a screenshot into your clipboard hit control + shift + command + 4; it'll give you a crosshair you can drag across the region you want to capture. Then come to GitHub and paste it into a comment field here. It'll spit out some code, but when you submit the comment (or hit preview) it'll show as an image. For example: 

image

**Comment by rgilman** [comment]
@DavidScottBernstein, looks good! I think we will want to tweak the date formatting but I feel it's OK for now.

**Pull request merged**
